"""auto update

Revision ID: 172e97d685cb
Revises: 
Create Date: 2026-02-20 09:11:04.912865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172e97d685cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('entregador_padrao_id', sa.String(), nullable=True),
    sa.Column('entregador_padrao_nome', sa.String(), nullable=True),
    sa.Column('motorista_id', sa.String(), nullable=True),
    sa.Column('motorista_nome', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cidades_id'), 'cidades', ['id'], unique=False)
    op.create_table('confirmacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('cidade_nome', sa.String(), nullable=True),
    sa.Column('entregador_id', sa.String(), nullable=True),
    sa.Column('entregador_nome', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmacoes_id'), 'confirmacoes', ['id'], unique=False)
    op.create_table('pacotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_rastreio', sa.String(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('cidade_nome', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacotes_id'), 'pacotes', ['id'], unique=False)
    op.create_table('perfis_usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.Column('cidade_vinculada_id', sa.Integer(), nullable=True),
    sa.Column('cidade_vinculada_nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfis_usuarios_id'), 'perfis_usuarios', ['id'], unique=False)
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_rastreio', sa.String(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('cidade_nome', sa.String(), nullable=True),
    sa.Column('motorista_id', sa.String(), nullable=True),
    sa.Column('motorista_nome', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transferencias_id'), 'transferencias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transferencias_id'), table_name='transferencias')
    op.drop_table('transferencias')
    op.drop_index(op.f('ix_perfis_usuarios_id'), table_name='perfis_usuarios')
    op.drop_table('perfis_usuarios')
    op.drop_index(op.f('ix_pacotes_id'), table_name='pacotes')
    op.drop_table('pacotes')
    op.drop_index(op.f('ix_confirmacoes_id'), table_name='confirmacoes')
    op.drop_table('confirmacoes')
    op.drop_index(op.f('ix_cidades_id'), table_name='cidades')
    op.drop_table('cidades')
    # ### end Alembic commands ###