"""auto update

Revision ID: dc60d3786f6a
Revises: e73439e1315b
Create Date: 2026-02-20 15:09:57.033761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc60d3786f6a'
down_revision: Union[str, Sequence[str], None] = 'e73439e1315b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumos_triagem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('cidade_nome', sa.String(), nullable=False),
    sa.Column('quantidade_pacotes', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.String(), nullable=True),
    sa.Column('auxiliar_responsavel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumos_triagem_id'), 'resumos_triagem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumos_triagem_id'), table_name='resumos_triagem')
    op.drop_table('resumos_triagem')
    # ### end Alembic commands ###