"""auto update

Revision ID: e73439e1315b
Revises: 172e97d685cb
Create Date: 2026-02-20 14:53:00.677994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73439e1315b'
down_revision: Union[str, Sequence[str], None] = '172e97d685cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leituras_auxiliar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_rastreio', sa.String(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('cidade_nome', sa.String(), nullable=False),
    sa.Column('data_vencimento', sa.String(), nullable=True),
    sa.Column('auxiliar_nome', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leituras_auxiliar_id'), 'leituras_auxiliar', ['id'], unique=False)
    op.create_table('rotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motorista_id', sa.String(), nullable=False),
    sa.Column('motorista_nome', sa.String(), nullable=False),
    sa.Column('veiculo_tipo', sa.String(), nullable=False),
    sa.Column('cidades_ids', sa.String(), nullable=True),
    sa.Column('cidades_nomes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rotas_id'), 'rotas', ['id'], unique=False)
    op.add_column('cidades', sa.Column('veiculo_tipo', sa.String(), nullable=True))
    op.add_column('pacotes', sa.Column('data_vencimento', sa.String(), nullable=True))
    op.add_column('pacotes', sa.Column('auxiliar_responsavel', sa.String(), nullable=True))
    op.add_column('perfis_usuarios', sa.Column('ativo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfis_usuarios', 'ativo')
    op.drop_column('pacotes', 'auxiliar_responsavel')
    op.drop_column('pacotes', 'data_vencimento')
    op.drop_column('cidades', 'veiculo_tipo')
    op.drop_index(op.f('ix_rotas_id'), table_name='rotas')
    op.drop_table('rotas')
    op.drop_index(op.f('ix_leituras_auxiliar_id'), table_name='leituras_auxiliar')
    op.drop_table('leituras_auxiliar')
    # ### end Alembic commands ###